package net.kurobako.cef4j.codegen.ipc

/** Emits a single-header C++ struct + encode/decode functions matching the Java side wire format.
  *
  * Layout: same little-endian order, same length-prefixed strings/bytes. Output is intended to be included into the
  * cef4j-runtime-server build, replacing the inline byte parsing in {@code main.cpp}.
  *
  * One header per spec; no inline-defined codecs in a `.cpp` to keep the runtime server's build flat.
  */
object CppEmitter {

  /** Returns a self-contained C++17 header. */
  def emit(spec: MessageSpec): String = {
    val guardName = (spec.packageName.replace('.', '_').toUpperCase + "_" + camelToSnake(spec.className).toUpperCase
      + "_H_")
    val ns       = spec.packageName.replace('.', '_').toLowerCase
    val cls      = spec.className
    val fields   = renderFields(spec)
    val sizeBody = renderEncodedSizeBody(spec)
    val encBody  = renderEncodeBody(spec)
    val decBody  = renderDecodeBody(spec)
    val decPos   = "        std::size_t pos = 0;"
    // Nested DataStruct fields reference other generated headers; pull them in via #include so the compile
    // graph resolves. Each spec gets its own .h file (Main.scala writes one per spec), so naming matches.
    val nestedIncludes = spec.fields.collect {
      case FieldSpec(_, FieldType.DataStruct(cefName)) => SpecDeriver.cefStructToClassName(cefName)
    }.distinct.map(c => s"""#include "$c.h"""").mkString("\n")

    s"""// Generated by net.kurobako.cef4j.codegen.ipc — do not edit by hand.
       |#ifndef $guardName
       |#define $guardName
       |
       |#include <cstdint>
       |#include <cstring>
       |#include <stdexcept>
       |#include <string>
       |#include <vector>
       |$nestedIncludes
       |
       |namespace $ns {
       |
       |struct $cls {
       |    static constexpr int32_t kMessageId = ${spec.messageId};
       |
       |$fields
       |    /** Number of payload bytes that {@link encodeInto} writes for this instance. */
       |    std::size_t encodedSize() const noexcept {
       |        return $sizeBody;
       |    }
       |
       |    /** Writes exactly {@link encodedSize} bytes starting at {@code dst}. */
       |    void encodeInto(std::uint8_t* dst) const noexcept {
       |$encBody
       |    }
       |
       |    /** Reads a $cls from a payload starting at {@code src}; {@code len} bounds the buffer. */
       |    static $cls decode(const std::uint8_t* src, std::size_t len) {
       |        $cls out;
       |$decPos
       |        [[maybe_unused]] auto requireAvailable = [&](std::size_t count) {
       |            if (pos > len || count > len - pos)
       |                throw std::invalid_argument("truncated $cls payload");
       |        };
       |$decBody
       |        return out;
       |    }
       |};
       |
       |} // namespace $ns
       |
       |#endif // $guardName
       |""".stripMargin
  }

  private def camelToSnake(s: String): String =
    s.foldLeft(StringBuilder()) { (sb, c) =>
      if (c.isUpper && sb.nonEmpty) sb.append('_').append(c.toLower)
      else sb.append(c.toLower)
    }.toString

  private def cppType(ty: FieldType): String = ty match {
    case FieldType.I32                 => "std::int32_t"
    case FieldType.I64                 => "std::int64_t"
    case FieldType.Bool                => "bool"
    case FieldType.Utf8String          => "std::string"
    case FieldType.Bytes               => "std::vector<std::uint8_t>"
    case FieldType.StringList          => "std::vector<std::string>"
    case FieldType.RemoteHandle        => "std::int32_t" // resolved via runtime-server-side HandleTable
    case FieldType.DataStruct(cefName) => SpecDeriver.cefStructToClassName(cefName)
  }

  private def renderFields(spec: MessageSpec): String =
    spec.fields.map { f =>
      val init = f.ty match {
        case FieldType.I32 | FieldType.I64 | FieldType.RemoteHandle => " = 0"
        case FieldType.Bool                                         => " = false"
        case _                                                      => ""
      }
      s"    ${cppType(f.ty)} ${f.name}$init;"
    }.mkString("\n") + "\n"

  private def fixedSize(ty: FieldType): Int = ty match {
    case FieldType.I32                          => 4
    case FieldType.I64                          => 8
    case FieldType.Bool                         => 1
    case FieldType.Utf8String | FieldType.Bytes => 4
    case FieldType.StringList                   => 4
    case FieldType.RemoteHandle                 => 4
    case FieldType.DataStruct(_)                => 0
  }

  private def variableSizeExpr(field: FieldSpec): Option[String] = field.ty match {
    case FieldType.Utf8String => Some(s"${field.name}.size()")
    case FieldType.Bytes      => Some(s"${field.name}.size()")
    case FieldType.StringList =>
      // 4-byte length prefix per element + total UTF-8 byte count. Compute via accumulation since
      // there's no constexpr expression.
      Some(s"[&]() { std::size_t n = 0; for (const auto& __s : ${field.name}) n += 4 + __s.size(); return n; }()")
    case FieldType.DataStruct(_) => Some(s"${field.name}.encodedSize()")
    case _                       => None
  }

  private def renderEncodedSizeBody(spec: MessageSpec): String = {
    val fixed    = spec.fields.map(f => fixedSize(f.ty)).sum
    val variable = spec.fields.flatMap(variableSizeExpr).mkString(" + ")
    if (variable.isEmpty) fixed.toString else s"$fixed + $variable"
  }

  /** Reusable little-endian write helpers. To keep generated code self-contained, the helpers are inlined directly here
    * instead of a shared header — keeps each generated file independently buildable.
    */
  private val writeI32 = (offsetVar: String, valExpr: String) =>
    s"""        {
       |            std::uint32_t v = static_cast<std::uint32_t>($valExpr);
       |            dst[$offsetVar + 0] = static_cast<std::uint8_t>(v & 0xFF);
       |            dst[$offsetVar + 1] = static_cast<std::uint8_t>((v >> 8) & 0xFF);
       |            dst[$offsetVar + 2] = static_cast<std::uint8_t>((v >> 16) & 0xFF);
       |            dst[$offsetVar + 3] = static_cast<std::uint8_t>((v >> 24) & 0xFF);
       |            $offsetVar += 4;
       |        }""".stripMargin

  private val writeI64 = (offsetVar: String, valExpr: String) =>
    s"""        {
       |            std::uint64_t v = static_cast<std::uint64_t>($valExpr);
       |            for (int i = 0; i < 8; ++i) dst[$offsetVar + i] = static_cast<std::uint8_t>((v >> (i * 8)) & 0xFF);
       |            $offsetVar += 8;
       |        }""".stripMargin

  private val readI32 = (offsetVar: String, srcVar: String) =>
    s"static_cast<std::int32_t>(static_cast<std::uint32_t>($srcVar[$offsetVar]) | (static_cast<std::uint32_t>($srcVar[$offsetVar + 1]) << 8) | (static_cast<std::uint32_t>($srcVar[$offsetVar + 2]) << 16) | (static_cast<std::uint32_t>($srcVar[$offsetVar + 3]) << 24))"

  private val readI64 = (offsetVar: String, srcVar: String) =>
    s"static_cast<std::int64_t>(static_cast<std::uint64_t>($srcVar[$offsetVar]) | (static_cast<std::uint64_t>($srcVar[$offsetVar + 1]) << 8) | (static_cast<std::uint64_t>($srcVar[$offsetVar + 2]) << 16) | (static_cast<std::uint64_t>($srcVar[$offsetVar + 3]) << 24) | (static_cast<std::uint64_t>($srcVar[$offsetVar + 4]) << 32) | (static_cast<std::uint64_t>($srcVar[$offsetVar + 5]) << 40) | (static_cast<std::uint64_t>($srcVar[$offsetVar + 6]) << 48) | (static_cast<std::uint64_t>($srcVar[$offsetVar + 7]) << 56))"

  private def renderEncodeBody(spec: MessageSpec): String = {
    val pre   = if (spec.fields.isEmpty) Nil else List("        std::size_t pos = 0;")
    val parts = spec.fields.flatMap { f =>
      f.ty match {
        case FieldType.I32 | FieldType.RemoteHandle => List(writeI32("pos", f.name))
        case FieldType.I64                          => List(writeI64("pos", f.name))
        case FieldType.Bool                         =>
          List(s"        dst[pos] = static_cast<std::uint8_t>(${f.name} ? 1 : 0);", "        pos += 1;")
        case FieldType.Utf8String =>
          List(
            writeI32("pos", s"${f.name}.size()"),
            s"        std::memcpy(dst + pos, ${f.name}.data(), ${f.name}.size());",
            s"        pos += ${f.name}.size();"
          )
        case FieldType.Bytes =>
          List(
            writeI32("pos", s"${f.name}.size()"),
            s"        if (!${f.name}.empty()) std::memcpy(dst + pos, ${f.name}.data(), ${f.name}.size());",
            s"        pos += ${f.name}.size();"
          )
        case FieldType.StringList =>
          // count prefix, then for each string: length prefix + raw UTF-8 bytes
          List(
            writeI32("pos", s"${f.name}.size()"),
            s"        for (const auto& __s : ${f.name}) {",
            writeI32("pos", "__s.size()"),
            s"            std::memcpy(dst + pos, __s.data(), __s.size());",
            s"            pos += __s.size();",
            s"        }"
          )
        case FieldType.DataStruct(_) =>
          // Nested struct rides inline. Its own encodeInto writes from `dst+pos`; pos advances by the nested
          // encodedSize. Because we generate forward references to types we may not have included yet, the
          // nested struct's header must be #included by the user (Main.scala emits one .h per struct so the
          // compile graph resolves naturally).
          List(
            s"        ${f.name}.encodeInto(dst + pos);",
            s"        pos += ${f.name}.encodedSize();"
          )
      }
    }
    (pre ++ parts).mkString("\n")
  }

  private def renderDecodeBody(spec: MessageSpec): String =
    spec.fields.flatMap { f =>
      f.ty match {
        case FieldType.I32 | FieldType.RemoteHandle =>
          List(
            "        requireAvailable(4);",
            s"        out.${f.name} = ${readI32("pos", "src")};",
            "        pos += 4;"
          )
        case FieldType.I64 => List(
            "        requireAvailable(8);",
            s"        out.${f.name} = ${readI64("pos", "src")};",
            "        pos += 8;"
          )
        case FieldType.Bool =>
          List("        requireAvailable(1);", s"        out.${f.name} = src[pos] != 0;", "        pos += 1;")
        case FieldType.Utf8String =>
          List(
            s"        {",
            s"            requireAvailable(4);",
            s"            std::int32_t n = ${readI32("pos", "src")};",
            s"            pos += 4;",
            s"            if (n < 0) throw std::invalid_argument(\"negative length for ${f.name}\");",
            s"            requireAvailable(static_cast<std::size_t>(n));",
            s"            out.${f.name}.assign(reinterpret_cast<const char*>(src + pos), static_cast<std::size_t>(n));",
            s"            pos += static_cast<std::size_t>(n);",
            s"        }"
          )
        case FieldType.Bytes =>
          List(
            s"        {",
            s"            requireAvailable(4);",
            s"            std::int32_t n = ${readI32("pos", "src")};",
            s"            pos += 4;",
            s"            if (n < 0) throw std::invalid_argument(\"negative length for ${f.name}\");",
            s"            requireAvailable(static_cast<std::size_t>(n));",
            s"            out.${f.name}.assign(src + pos, src + pos + n);",
            s"            pos += static_cast<std::size_t>(n);",
            s"        }"
          )
        case FieldType.StringList =>
          List(
            s"        {",
            s"            requireAvailable(4);",
            s"            std::int32_t cnt = ${readI32("pos", "src")};",
            s"            pos += 4;",
            s"            if (cnt < 0) throw std::invalid_argument(\"negative count for ${f.name}\");",
            s"            if (static_cast<std::size_t>(cnt) > (len - pos) / 4) throw std::invalid_argument(\"invalid count for ${f.name}\");",
            s"            out.${f.name}.reserve(static_cast<std::size_t>(cnt));",
            s"            for (std::int32_t __i = 0; __i < cnt; ++__i) {",
            s"                requireAvailable(4);",
            s"                std::int32_t slen = ${readI32("pos", "src")};",
            s"                pos += 4;",
            s"                if (slen < 0) throw std::invalid_argument(\"negative string length for ${f.name}\");",
            s"                requireAvailable(static_cast<std::size_t>(slen));",
            s"                out.${f.name}.emplace_back(reinterpret_cast<const char*>(src + pos), static_cast<std::size_t>(slen));",
            s"                pos += static_cast<std::size_t>(slen);",
            s"            }",
            s"        }"
          )
        case FieldType.DataStruct(cefName) =>
          val cls = SpecDeriver.cefStructToClassName(cefName)
          List(
            s"        out.${f.name} = $cls::decode(src + pos, len - pos);",
            s"        requireAvailable(out.${f.name}.encodedSize());",
            s"        pos += out.${f.name}.encodedSize();"
          )
      }
    }.mkString("\n")
}
