package net.kurobako.cef4j.codegen.ipc

/** Emits one C++ class per CEF HandlerStruct that the runtime server can hand back from `cef_client_t::get_X_handler`.
  * Each struct subclasses the corresponding `cef_<name>_t`, sets every callback to a lambda that encodes the matching
  * AST event and sends it via the runtime server's `IpcServer`.
  *
  * Callback param conversion mirrors the dispatcher in reverse:
  *   - `cef_browser_t*`/`cef_frame_t*`/etc. → `tables::X.insert(ptr)` to mint or reuse a handle id (dedupe is done
  *     inside HandleTable)
  *   - `cef_string_t*` (in callbacks) → `std::string` via `cef_string_to_utf8`
  *   - primitive scalars → as-is
  *
  * Output is a single `HandlerForwarders.h` that the runtime server includes once. The runtime server is responsible
  * for instantiating and exposing whichever forwarders it cares about (typically via `CefClient::get_X_handler`).
  *
  * Methods whose param shape isn't supported get an empty callback (no-op), so the forwarder still satisfies the CEF
  * struct's contract and won't crash if CEF invokes it.
  */
object CppHandlerForwarderEmitter {

  case class ForwarderInputs(
      handlers: List[HandlerSpec],
      facadeStructs: Set[String], // structs that have HandleTables (live in `tables::`)
      capiHeaders: List[String],
      packageName: String,
      // (handler struct name, cef_client_t getter name) pairs — used by wireClient to bind every forwarder
      // we have for a CefClient getter. Empty means wireClient is omitted.
      clientGetters: Map[String, String] = Map.empty
  )

  def emit(in: ForwarderInputs): String = {
    val ns           = in.packageName.replace('.', '_').toLowerCase
    val capiIncludes = in.capiHeaders.sorted.map(h => s"""#include "$h"""").mkString("\n")
    // Each handler references one Event class per supported method; deduplicate.
    val eventIncludes = in.handlers
      .flatMap(_.methods.flatMap(m => m.eventClassName :: m.responseClassName.toList))
      .distinct
      .sorted
      .map(c => s"""#include "$c.h"""")
      .mkString("\n")
    val classes = in.handlers.map(h => renderHandlerClass(h, ns, in.facadeStructs)).mkString("\n\n")
    // wireClient binds every forwarder whose handler is exposed via cef_client_t::get_X_handler. Only emit
    // entries we actually have a forwarder for, so partial codegen runs (or filtered handler sets) work too.
    val handlerSet   = in.handlers.map(_.cefStructName).toSet
    val wireBindings = in.clientGetters.toList.collect {
      case (handlerStruct, getterName) if handlerSet.contains(handlerStruct) =>
        val cls          = forwarderClassName(handlerStruct)
        val global       = s"g_${decapitalize(cls)}"
        val handlerCType = handlerStruct
        s"""    client->$getterName = [](cef_client_t* /*self*/) -> $handlerCType* {
           |        auto* h    = &$global;
           |        auto* base = reinterpret_cast<cef_base_ref_counted_t*>(h);
           |        base->add_ref(base);
           |        return h;
           |    };""".stripMargin
    }
    val wireClient =
      if (wireBindings.isEmpty) ""
      else
        s"""
           |/** Sets every `cef_client_t::get_X_handler` for which a forwarder exists to a lambda that returns
           |  * the corresponding global. The runtime server calls this once during its CefClient construction; specific
           |  * getters can be overridden afterward to keep custom hand-written behavior (e.g. RenderHandler's
           |  * paint logic). */
           |inline void wireClient(cef_client_t* client) {
           |${wireBindings.mkString("\n")}
           |}
           |""".stripMargin

    s"""// Generated by net.kurobako.cef4j.codegen.ipc — do not edit by hand.
       |//
       |// One forwarder class per CEF HandlerStruct. Each callback encodes the matching AST event and sends it
       |// via IpcServer. Runtime server instantiates them and exposes via CefClient::get_X_handler queries.
       |#ifndef CEF4J_IPC_GEN_HANDLER_FORWARDERS_H_
       |#define CEF4J_IPC_GEN_HANDLER_FORWARDERS_H_
       |
       |#include <atomic>
       |#include <cstdint>
       |#include <cstring>
       |#include <string>
       |#include <type_traits>
       |#include <vector>
       |
       |#include "include/capi/cef_base_capi.h"
       |#include "include/internal/cef_string.h"
       |$capiIncludes
       |
       |#include <chrono>
       |
       |#include "Envelope.h"
       |#include "HandleTable.h"
       |#include "InterceptRegistry.h"
       |#include "IpcServer.h"
       |#include "Dispatcher.h"
       |
       |$eventIncludes
       |
       |namespace ${ns}_handlers {
       |
       |namespace gen      = $ns;
       |namespace gendisp  = ${ns}_dispatcher;
       |
       |/** Each forwarder writes to this single runtime-server-owned `IpcServer` (set once at startup, before any handler
       |  * fires). Null means "drop the event" — useful during shutdown so a late callback doesn't crash. */
       |inline cef4j::ipc::IpcServer* g_ipc = nullptr;
       |
       |/** Process-wide intercept waiter registry. Non-void handler callbacks block here for a JVM-supplied
       |  * return value before handing it back to CEF. Shares the same singleton main.cpp uses. */
       |inline cef4j::ipc::InterceptRegistry& g_intercepts = cef4j::ipc::intercepts();
       |
       |/** Sets the CEF refcount base for a forwarder. Forwarders are owned by the runtime server as `inline` globals so
       |  * their refcount stays positive across the process lifetime. */
       |template <typename T, typename CefStruct>
       |inline void initForwarderBase(cef_base_ref_counted_t* base) {
       |    base->size                  = sizeof(CefStruct);
       |    base->add_ref               = [](cef_base_ref_counted_t* self) {
       |        reinterpret_cast<T*>(self)->refCount.fetch_add(1, std::memory_order_relaxed);
       |    };
       |    base->release               = [](cef_base_ref_counted_t* self) -> int {
       |        auto* t = reinterpret_cast<T*>(self);
       |        if (t->refCount.fetch_sub(1, std::memory_order_acq_rel) == 1) {
       |            // Static lifetime; deletion is left to process exit.
       |            return 1;
       |        }
       |        return 0;
       |    };
       |    base->has_one_ref           = [](cef_base_ref_counted_t* self) -> int {
       |        return reinterpret_cast<T*>(self)->refCount.load(std::memory_order_acquire) == 1;
       |    };
       |    base->has_at_least_one_ref  = [](cef_base_ref_counted_t* self) -> int {
       |        return reinterpret_cast<T*>(self)->refCount.load(std::memory_order_acquire) >= 1;
       |    };
       |}
       |
       |inline std::string utf16ToUtf8(const cef_string_t* s) {
       |    if (!s || s->length == 0) return {};
       |    cef_string_utf8_t utf8{};
       |    cef_string_utf16_to_utf8(s->str, s->length, &utf8);
       |    std::string r(utf8.str, utf8.length);
       |    cef_string_utf8_clear(&utf8);
       |    return r;
       |}
       |
       |/** Coerce-to-int64 helper that handles both arithmetic types and pointer types uniformly. The forwarder
       |  * emit treats {@code FieldType.I64} as a generic 64-bit slot — but some CEF callback args are typedef'd
       |  * to a pointer (e.g. {@code cef_event_handle_t} = {@code XEvent*} on Linux), and {@code static_cast}
       |  * from a pointer to {@code int64_t} is invalid. {@code if constexpr} dispatches to the right cast.
       |  */
       |template <typename T>
       |inline std::int64_t toI64(T v) {
       |    if constexpr (std::is_pointer_v<T>) return reinterpret_cast<std::int64_t>(v);
       |    else return static_cast<std::int64_t>(v);
       |}
       |
       |$classes
       |$wireClient
       |} // namespace ${ns}_handlers
       |
       |#endif // CEF4J_IPC_GEN_HANDLER_FORWARDERS_H_
       |""".stripMargin
  }

  /** Per-handler class name: `cef_load_handler_t` → `LoadHandlerForwarder`. The CEF "Cef" prefix on the JVM-side
    * interface is dropped here for brevity since these are internal runtime-server types.
    */
  private def forwarderClassName(spec: HandlerSpec): String = forwarderClassName(spec.cefStructName)

  private def forwarderClassName(cefStruct: String): String =
    toCamelCase(stripCefPrefix(cefStruct)) + "Forwarder"

  private def stripCefPrefix(name: String): String = name.stripPrefix("cef_").stripSuffix("_t")

  private def toCamelCase(s: String): String =
    s.split('_').iterator.filter(_.nonEmpty).map(p => p.head.toUpper +: p.tail).mkString

  private def renderHandlerClass(spec: HandlerSpec, ns: String, facadeStructs: Set[String]): String = {
    val cls       = forwarderClassName(spec)
    val cefStruct = spec.cefStructName
    val callbacks = spec.methods.map(m => renderCallbackInit(m, cefStruct, facadeStructs)).mkString("\n")

    s"""struct $cls : $cefStruct {
       |    std::atomic<int> refCount{1};
       |
       |    $cls() : $cefStruct{} {
       |        initForwarderBase<$cls, $cefStruct>(reinterpret_cast<cef_base_ref_counted_t*>(this));
       |$callbacks
       |    }
       |};
       |
       |/** Single global instance — runtime server hands this out from `CefClient::get_X_handler` (or wherever). */
       |inline $cls g_${decapitalize(cls)};""".stripMargin
  }

  private def decapitalize(s: String): String =
    if (s.isEmpty) s else s.head.toLower +: s.tail

  /** Renders a single callback assignment like `on_load_end = [](...) { ... };`. If a param uses an unsupported shape
    * (e.g. RemoteHandle to a non-facade struct), the callback is set to a no-op so the forwarder still satisfies the
    * CEF struct's contract.
    */
  private def renderCallbackInit(m: HandlerMethod, cefStruct: String, facadeStructs: Set[String]): String = {
    // Determine whether every param is something we know how to encode.
    val unsupported = m.params.exists { p =>
      p.ty match {
        case FieldType.RemoteHandle => !m.handleStructByField.get(p.name).exists(facadeStructs.contains)
        case FieldType.Bytes        => true
        case _                      => false
      }
    }
    if (unsupported) {
      // Empty no-op signature: build the lambda using the CEF callback's actual params (we only have field
      // names + types, not the C type strings). Use `auto...` template params and ignore them.
      // Actually CEF callbacks take specific C types; can't use `auto...`. Skip emitting this callback.
      return s"        // ${m.cefMethodName}: skipped (unsupported param shape)"
    }
    // CEF callback signatures use scoped enum types (cef_transition_type_t, cef_event_flags_t, etc.) that
    // don't accept implicit int conversion under -fpermissive. Pull each param's declared type straight off
    // the function-pointer field via `fn_args<decltype(struct::method)>::template arg<N>` so the lambda
    // signature matches CEF exactly. Index 0 is `self`; user params start at 1.
    val fnTypeRef =
      s"gendisp::fn_args<decltype(static_cast<::$cefStruct*>(nullptr)->${m.cefMethodName})>"
    val cefParams = m.params.zipWithIndex.map { case (p, i) =>
      val argIdx = i + 1
      s"$fnTypeRef::template arg<$argIdx> ${p.name}"
    }
    val lambdaParams = (s"$fnTypeRef::template arg<0> /*self*/" :: cefParams).mkString(", ")
    val fieldAssigns = m.params.map { p =>
      p.ty match {
        case FieldType.I32          => s"            ev.${p.name} = static_cast<std::int32_t>(${p.name});"
        case FieldType.I64          => s"            ev.${p.name} = toI64(${p.name});"
        case FieldType.Bool         => s"            ev.${p.name} = ${p.name} != 0;"
        case FieldType.Utf8String   => s"            ev.${p.name} = utf16ToUtf8(${p.name});"
        case FieldType.RemoteHandle =>
          val struct = m.handleStructByField(p.name)
          val tbl    = decapitalize(toCamelCase(stripCefPrefix(struct)))
          s"            ev.${p.name} = gendisp::tables::$tbl.insert(${p.name});"
        case FieldType.Bytes         => "" // unreachable
        case FieldType.StringList    => "" // unreachable; deriveHandlerMethod skips StringList
        case FieldType.DataStruct(_) => "" // unreachable
      }
    }.mkString("\n")
    val eventEncode =
      s"""            gen::${m.eventClassName} ev;
         |$fieldAssigns
         |            std::vector<std::uint8_t> payload(ev.encodedSize());
         |            ev.encodeInto(payload.data());""".stripMargin
    m.returnType match {
      case None =>
        // Void-returning handler: send Kind::Event, fire-and-forget.
        s"""        ${m.cefMethodName} = []($lambdaParams) {
           |            if (!g_ipc) return;
           |$eventEncode
           |            g_ipc->send(cef4j::ipc::Kind::Event, 0, cef4j::ipc::kNoCorrId,
           |                        gen::${m.eventClassName}::kMessageId, payload.data(), payload.size());
           |        };""".stripMargin
      case Some(FieldType.Bool) =>
        // Non-void handler: encode the request, allocate a corrId, send Kind::Intercept, block on
        // InterceptRegistry::awaitResponse, decode the reply, return to CEF. Default-on-timeout = 0 (treat
        // CEF's "no JVM opinion" as the conservative default — don't block popups, allow navigation, etc.).
        // gendisp::cefRet handles the int→cef_X_t cast for the (rare) enum-typed return slots.
        val fnRef   = s"decltype(static_cast<::$cefStruct*>(nullptr)->${m.cefMethodName})"
        val respCls = m.responseClassName.getOrElse(m.eventClassName + "Response")
        s"""        ${m.cefMethodName} = []($lambdaParams) -> typename gendisp::fn_args<$fnRef>::result {
           |            if (!g_ipc) return gendisp::cefRet<$fnRef>(0);
           |$eventEncode
           |            std::int32_t corrId = g_intercepts.allocateCorrId();
           |            g_ipc->send(cef4j::ipc::Kind::Intercept, 0, corrId,
           |                        gen::${m.eventClassName}::kMessageId, payload.data(), payload.size());
           |            std::vector<std::uint8_t> respBytes;
           |            bool got = g_intercepts.awaitResponse(corrId, std::chrono::milliseconds(2000), respBytes);
           |            int answer = 0;
           |            if (got && !respBytes.empty()) {
           |                auto resp = gen::$respCls::decode(respBytes.data(), respBytes.size());
           |                answer = resp.result ? 1 : 0;
           |            }
           |            return gendisp::cefRet<$fnRef>(answer);
           |        };""".stripMargin
      case Some(_) =>
        // Should be filtered out by SpecDeriver, but keep a safe no-op fallback.
        s"        // ${m.cefMethodName}: skipped (unsupported return type)"
    }
  }
}
