package net.kurobako.cef4j.codegen.ipc

object CppJvmVisitorEmitter {

  case class Inputs(
      visitors: List[JvmVisitorSpec],
      capiHeaders: List[String], // relative paths from CEF dist root, e.g. "include/capi/cef_string_visitor_capi.h"
      packageName: String
  )

  def syntheticClassName(spec: JvmVisitorSpec): String =
    "Jvm" + spec.cefStructName.stripPrefix("cef_").stripSuffix("_t")
      .split('_').iterator.filter(_.nonEmpty).map(p => p.head.toUpper +: p.tail).mkString

  def emit(in: Inputs): String = {
    val ns            = in.packageName.replace('.', '_').toLowerCase
    val capiIncludes  = in.capiHeaders.sorted.map(h => s"""#include "$h"""").mkString("\n")
    val eventIncludes = in.visitors.map(_.eventClassName).distinct.sorted
      .map(c => s"""#include "$c.h"""").mkString("\n")
    val classes = in.visitors.map(renderSynthetic).mkString("\n\n")

    s"""// Generated by net.kurobako.cef4j.codegen.ipc — do not edit by hand.
       |//
       |// Synthetic cef_X_t subclasses for JVM-owned visitor types. The dispatcher creates these on demand
       |// when a facade method param's struct matches a registered visitor. Each carries a callbackId so the
       |// JVM can route the callback back to the correct registered Java visitor.
       |#ifndef CEF4J_IPC_GEN_JVM_VISITORS_H_
       |#define CEF4J_IPC_GEN_JVM_VISITORS_H_
       |
       |#include <atomic>
       |#include <cstdint>
       |#include <string>
       |#include <tuple>
       |#include <vector>
       |
       |#include "include/capi/cef_base_capi.h"
       |#include "include/internal/cef_string.h"
       |$capiIncludes
       |
       |#include "Envelope.h"
       |#include "IpcServer.h"
       |
       |$eventIncludes
       |
       |namespace ${ns}_visitors {
       |
       |namespace gen = $ns;
       |
       |/** Local copy of the dispatcher's fn_args template — same trick to extract callback signature param
       |  * types so our captureless lambda exactly matches CEF's function-pointer slot. */
       |template <typename F> struct jvm_fn_args;
       |template <typename R, typename... Args> struct jvm_fn_args<R (*)(Args...)> {
       |    using result = R;
       |    template <std::size_t N> using arg = std::tuple_element_t<N, std::tuple<Args...>>;
       |};
       |
       |/** UTF-16 → UTF-8 helper. Mirrors the one in HandlerForwarders; duplicated here to keep this header
       |  * standalone (callers may include only this). */
       |inline std::string jvmVisitorUtf16ToUtf8(const cef_string_t* s) {
       |    if (!s || s->length == 0) return {};
       |    cef_string_utf8_t utf8{};
       |    cef_string_utf16_to_utf8(s->str, s->length, &utf8);
       |    std::string r(utf8.str, utf8.length);
       |    cef_string_utf8_clear(&utf8);
       |    return r;
       |}
       |
       |$classes
       |
       |} // namespace ${ns}_visitors
       |
       |#endif // CEF4J_IPC_GEN_JVM_VISITORS_H_
       |""".stripMargin
  }

  private def renderSynthetic(v: JvmVisitorSpec): String = {
    val cefStruct      = v.cefStructName
    val syntheticCls   = syntheticClassName(v)
    val callbackMethod = v.cefMethodName
    // Use exact CEF callback types, including scoped enums.
    val fnTypeRef = s"jvm_fn_args<decltype($cefStruct::$callbackMethod)>"
    val cefParams = v.params.zipWithIndex.map { case (p, i) =>
      s"$fnTypeRef::template arg<${i + 1}> ${p.name}"
    }
    val lambdaParams = (s"$fnTypeRef::template arg<0> selfPtr" :: cefParams).mkString(", ")
    val fieldAssigns = v.params.map { p =>
      p.ty match {
        case FieldType.I32        => s"            ev.${p.name} = static_cast<std::int32_t>(${p.name});"
        case FieldType.I64        => s"            ev.${p.name} = static_cast<std::int64_t>(${p.name});"
        case FieldType.Bool       => s"            ev.${p.name} = ${p.name} != 0;"
        case FieldType.Utf8String => s"            ev.${p.name} = jvmVisitorUtf16ToUtf8(${p.name});"
        case _                    => s"            // ${p.name}: skipped (unsupported wire shape)"
      }
    }.mkString("\n")
    s"""struct $syntheticCls : $cefStruct {
       |    std::atomic<int> refCount{1};
       |    std::int32_t callbackId;
       |    cef4j::ipc::IpcServer* ipc;
       |
       |    $syntheticCls(std::int32_t cbId, cef4j::ipc::IpcServer* server)
       |            : $cefStruct{}, callbackId(cbId), ipc(server) {
       |        auto* selfBase              = reinterpret_cast<cef_base_ref_counted_t*>(this);
       |        selfBase->size              = sizeof($cefStruct);
       |        selfBase->add_ref           = [](cef_base_ref_counted_t* self) {
       |            reinterpret_cast<$syntheticCls*>(self)->refCount.fetch_add(1, std::memory_order_relaxed);
       |        };
       |        selfBase->release           = [](cef_base_ref_counted_t* self) -> int {
       |            auto* v = reinterpret_cast<$syntheticCls*>(self);
       |            if (v->refCount.fetch_sub(1, std::memory_order_acq_rel) == 1) {
       |                delete v;
       |                return 1;
       |            }
       |            return 0;
       |        };
       |        selfBase->has_one_ref       = [](cef_base_ref_counted_t* self) -> int {
       |            return reinterpret_cast<$syntheticCls*>(self)->refCount.load(std::memory_order_acquire) == 1;
       |        };
       |        selfBase->has_at_least_one_ref = [](cef_base_ref_counted_t* self) -> int {
       |            return reinterpret_cast<$syntheticCls*>(self)->refCount.load(std::memory_order_acquire) >= 1;
       |        };
       |        $callbackMethod = []($lambdaParams) {
       |            // Captureless lambdas can't close over `this`; recover via the self pointer CEF always
       |            // passes as arg 0. The cef_X_t struct is the first base, so the cast is well-defined.
       |            auto* v = reinterpret_cast<$syntheticCls*>(selfPtr);
       |            if (!v->ipc) return;
       |            gen::${v.eventClassName} ev;
       |            ev.callbackId = v->callbackId;
       |$fieldAssigns
       |            std::vector<std::uint8_t> wire(ev.encodedSize());
       |            ev.encodeInto(wire.data());
       |            v->ipc->send(cef4j::ipc::Kind::Event, 0, cef4j::ipc::kNoCorrId,
       |                         gen::${v.eventClassName}::kMessageId, wire.data(), wire.size());
       |        };
       |    }
       |};
       |
       |/** Convenience factory — returns a ${cefStruct}* with refcount=1 ready to hand to a CEF method. */
       |inline $cefStruct* make$syntheticCls(std::int32_t callbackId, cef4j::ipc::IpcServer* ipc) {
       |    return reinterpret_cast<$cefStruct*>(new $syntheticCls(callbackId, ipc));
       |}""".stripMargin
  }
}
