package net.kurobako.cef4j.codegen.ipc

/** Emits `RendererDispatcher.h` — the renderer-side counterpart to {@link CppDispatcherEmitter}. The browser-side
  * dispatcher relays renderer-affinity Requests via `cef4j_renderer_req` process_message; the runtime server, when
  * running as the renderer subprocess, calls into this dispatcher on receipt to decode the Request, look up the
  * receiver in the per-struct HandleTable, enter the frame's V8 context, invoke the C-API method, encode the Response,
  * and ship it back as `cef4j_renderer_resp` to the browser. The browser-side `Client::on_process_message_received`
  * then decodes the envelope and replies as Kind::Response on the IPC wire.
  *
  * Reuses the `${ns}_dispatcher::tables::*` HandleTables — the runtime server binary is the same executable for both
  * browser and renderer subprocess, but the address spaces are independent so each process has its own table state.
  *
  * Supported method shapes (similar to {@link CppDispatcherEmitter#isDispatchable}):
  *   - Receiver: a renderer-affinity facade struct (cef_v8_*, cef_dom*).
  *   - Params: I32/I64/Bool/Utf8String, plus RemoteHandle when the C struct is itself a facade (browser- or
  *     renderer-affinity — the table exists for both).
  *   - Return: Void or any of the same primitive/string types, or RemoteHandle when the result struct is a known
  *     facade.
  *
  * Anything else is skipped — we don't ship partial dispatchers.
  */
object CppRendererDispatcherEmitter {

  case class RendererInputs(
      facades: List[FacadeSpec],
      messageSpecs: List[MessageSpec],
      capiHeaders: List[String],
      packageName: String
  )

  def emit(in: RendererInputs): String = {
    val ns                = in.packageName.replace('.', '_').toLowerCase
    val facadeStructs     = in.facades.map(_.cefStructName).toSet
    val rendererFacades   = in.facades.filter(_.affinity == ProcessAffinity.Renderer)
    val dispatchableByFac =
      rendererFacades
        .map(f => f -> f.methods.filter(m => isDispatchable(m, facadeStructs)))
        .filter(_._2.nonEmpty)

    val capiIncludes = in.capiHeaders.sorted.map(h => s"""#include "$h"""").mkString("\n")
    val genIncludes  = dispatchableByFac.flatMap { case (_, ms) =>
      ms.flatMap(m => List(m.requestClassName, m.responseClassName))
    }.distinct.sorted.map(c => s"""#include "$c.h"""").mkString("\n")

    val cases = dispatchableByFac.flatMap { case (f, ms) =>
      ms.map(m => renderCase(f, m, ns, in.messageSpecs))
    }.mkString("\n")

    val dispatchableCount = dispatchableByFac.map(_._2.size).sum
    val skippedCount      = rendererFacades.flatMap(_.methods).size - dispatchableCount

    s"""// Generated by net.kurobako.cef4j.codegen.ipc — do not edit by hand.
       |//
       |// Renderer-affinity dispatchable methods covered: $dispatchableCount
       |// Renderer-affinity methods skipped (unsupported shape): $skippedCount
       |#ifndef CEF4J_IPC_GEN_RENDERER_DISPATCHER_H_
       |#define CEF4J_IPC_GEN_RENDERER_DISPATCHER_H_
       |
       |#include <cstdint>
       |#include <cstring>
       |#include <string>
       |#include <vector>
       |
       |#include "include/capi/cef_base_capi.h"
       |#include "include/capi/cef_frame_capi.h"
       |#include "include/capi/cef_process_message_capi.h"
       |#include "include/capi/cef_values_capi.h"
       |#include "include/internal/cef_string.h"
       |#include "include/internal/cef_string_list.h"
       |$capiIncludes
       |
       |#include "Dispatcher.h"
       |
       |$genIncludes
       |
       |namespace ${ns}_renderer_dispatcher {
       |
       |namespace tables = ${ns}_dispatcher::tables;
       |using ScopedCefString = ${ns}_dispatcher::ScopedCefString;
       |using ${ns}_dispatcher::insertOrRelease;
       |
       |/** Wraps a `cef_v8_context_t*` so callers can `if (ctx) ctx->enter(...)` and have the matching `exit` and
       |  * release fire as scope ends. The C-API `cef_v8_context_t::enter`/`exit` are paired; missing `exit` would
       |  * leave the renderer in a sticky V8 state. The release happens regardless of enter success.
       |  */
       |class ScopedV8Context {
       |public:
       |    explicit ScopedV8Context(cef_v8_context_t* ctx) : ctx_(ctx), entered_(false) {
       |        if (ctx_) entered_ = ctx_->enter(ctx_) != 0;
       |    }
       |    ~ScopedV8Context() {
       |        if (ctx_) {
       |            if (entered_) ctx_->exit(ctx_);
       |            auto* base = reinterpret_cast<cef_base_ref_counted_t*>(ctx_);
       |            base->release(base);
       |        }
       |    }
       |    ScopedV8Context(const ScopedV8Context&) = delete;
       |    ScopedV8Context& operator=(const ScopedV8Context&) = delete;
       |    bool entered() const { return entered_; }
       |private:
       |    cef_v8_context_t* ctx_;
       |    bool entered_;
       |};
       |
       |/** Sends a packaged response back to the browser process via `frame->send_process_message`. Mirrors the
       |  * envelope format the browser-side relay sends: args = [corrId, messageId, payload bytes]. CEF takes
       |  * ownership of `msg` — do not release it ourselves.
       |  */
       |inline void sendResponseEnvelope(cef_frame_t* frame, const char* envelopeName, std::int32_t corrId,
       |                                 std::int32_t messageId, const std::uint8_t* payload, std::size_t size) {
       |    cef_string_t name{};
       |    cef_string_utf8_to_utf16(envelopeName, std::strlen(envelopeName), &name);
       |    cef_process_message_t* msg = cef_process_message_create(&name);
       |    cef_string_clear(&name);
       |    cef_list_value_t* args = msg->get_argument_list(msg);
       |    if (args) {
       |        args->set_int(args, 0, corrId);
       |        args->set_int(args, 1, messageId);
       |        cef_binary_value_t* binary = cef_binary_value_create(payload, size);
       |        if (binary) {
       |            // `set_binary` adopts our +1 — releasing here is a double-decrement that crashes the
       |            // renderer subprocess. Same contract as `set_string`.
       |            args->set_binary(args, 2, binary);
       |        }
       |        auto* ab = reinterpret_cast<cef_base_ref_counted_t*>(args);
       |        ab->release(ab);
       |    }
       |    frame->send_process_message(frame, PID_BROWSER, msg);
       |}
       |
       |/** Sends an empty `cef4j_renderer_err` response (8-byte ReceiverGone payload) so the JVM-side future fails
       |  * with CefRemoteException. The browser-side translates `_err` to Kind::Error on the IPC wire.
       |  */
       |inline void sendReceiverGone(cef_frame_t* frame, std::int32_t corrId, std::int32_t messageId) {
       |    static const std::uint8_t kReceiverGonePayload[8] = {0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
       |    sendResponseEnvelope(frame, "cef4j_renderer_err", corrId, messageId,
       |                          kReceiverGonePayload, sizeof(kReceiverGonePayload));
       |}
       |
       |/** Returns true iff the messageId was recognised and a response (success or error) was sent back to the
       |  * browser process. Caller (renderer's on_process_message_received) should fall through for unknown ids.
       |  */
       |inline bool dispatch(cef_frame_t* frame, std::int32_t corrId, std::int32_t messageId,
       |                     const std::vector<std::uint8_t>& payload) {
       |    namespace gen = $ns;
       |    switch (messageId) {
       |$cases
       |        default:
       |            return false;
       |    }
       |}
       |
       |} // namespace ${ns}_renderer_dispatcher
       |
       |#endif // CEF4J_IPC_GEN_RENDERER_DISPATCHER_H_
       |""".stripMargin
  }

  /** Filter to methods we can codegen on the renderer side. Same shape rules as the browser dispatcher's, just scoped
    * to renderer-affinity receivers.
    */
  private def isDispatchable(m: FacadeMethod, facadeStructs: Set[String]): Boolean = {
    def fieldOk(name: String, ty: FieldType): Boolean = ty match {
      case FieldType.I32 | FieldType.I64 | FieldType.Bool | FieldType.Utf8String => true
      case FieldType.RemoteHandle                                                =>
        m.handleStructByField.get(name).exists(facadeStructs.contains)
      case _ => false
    }
    val paramsOk = m.explicitParams.forall(p => fieldOk(p.name, p.ty))
    val resultOk = m.resultField match {
      case None    => true
      case Some(f) => fieldOk("result", f.ty)
    }
    paramsOk && resultOk
  }

  /** Same camelCase rule as `CppDispatcherEmitter.tableFieldName` — kept private so the two emitters can drift
    * independently if needed, but they currently match.
    */
  private def tableFieldName(cefStruct: String): String = {
    val core = cefStruct.stripPrefix("cef_").stripSuffix("_t")
    core.split('_').iterator.zipWithIndex.map { case (p, i) =>
      if (i == 0) p else p.headOption.fold("")(_.toUpper.toString) + p.drop(1)
    }.mkString
  }

  private def renderCase(
      f: FacadeSpec,
      m: FacadeMethod,
      ns: String,
      messageSpecs: List[MessageSpec]
  ): String = {
    val req       = m.requestClassName
    val resp      = m.responseClassName
    val table     = tableFieldName(f.cefStructName)
    val cFn       = m.cefMethodName
    val msgIdExpr = s"gen::$req::kMessageId"

    // Param decode + per-param prelude (string materialise / handle lookup).
    val paramPrelude = m.explicitParams.flatMap { p =>
      p.ty match {
        case FieldType.Utf8String =>
          List(s"            ScopedCefString ${p.name}_cef(req.${p.name});")
        case FieldType.RemoteHandle =>
          val struct = m.handleStructByField(p.name)
          val tbl    = tableFieldName(struct)
          List(
            s"            $struct* ${p.name}_ptr = req.${p.name} != 0 ? tables::$tbl.retain(req.${p.name}) : nullptr;"
          )
        case _ => Nil
      }
    }

    val paramPostlude = m.explicitParams.flatMap { p =>
      p.ty match {
        case FieldType.RemoteHandle =>
          List(
            s"""            if (${p.name}_ptr) {
               |                auto* ${p.name}_base = reinterpret_cast<cef_base_ref_counted_t*>(${p.name}_ptr);
               |                ${p.name}_base->release(${p.name}_base);
               |            }""".stripMargin
          )
        case _ => Nil
      }
    }

    // CEF's enum-typed args need a static_cast from int32_t to the receiver method's exact arg type. The
    // browser dispatcher uses the `cefArg<F, N>` template from Dispatcher.h (which we re-import via the
    // included header). Same pattern here so cef_v8_propertyattribute_t etc. accept our wire ints.
    val cFnRef  = s"receiver->$cFn"
    val argList = ("receiver" :: m.explicitParams.zipWithIndex.map { case (p, idx) =>
      val cArgIdx = idx + 1 // self at index 0
      p.ty match {
        case FieldType.Bool =>
          s"${ns}_dispatcher::cefArg<decltype($cFnRef), $cArgIdx>(req.${p.name} ? 1 : 0)"
        case FieldType.I32 | FieldType.I64 =>
          s"${ns}_dispatcher::cefArg<decltype($cFnRef), $cArgIdx>(req.${p.name})"
        case FieldType.Utf8String   => s"${p.name}_cef.get()"
        case FieldType.RemoteHandle => s"${p.name}_ptr"
        case _                      => s"req.${p.name}"
      }
    }).mkString(", ")

    val callAndRespond = m.resultField match {
      case None =>
        s"""            receiver->$cFn($argList);
           |${paramPostlude.mkString("\n")}
           |            std::vector<std::uint8_t> respPayload;
           |            sendResponseEnvelope(frame, "cef4j_renderer_resp", corrId, messageId,
           |                                  respPayload.data(), respPayload.size());""".stripMargin
      case Some(field) =>
        val resultStruct         = m.handleStructByField.get("result")
        val (cppRetType, assign) = field.ty match {
          case FieldType.I32        => ("int", "static_cast<std::int32_t>(rawResult)")
          case FieldType.I64        => ("int64_t", "static_cast<std::int64_t>(rawResult)")
          case FieldType.Bool       => ("int", "rawResult != 0")
          case FieldType.Utf8String =>
            ("cef_string_userfree_t", "ScopedCefString::take(rawResult).toUtf8()")
          case FieldType.RemoteHandle =>
            val tbl = resultStruct.map(tableFieldName).getOrElse("nullptr_table")
            (s"${resultStruct.get}*", s"insertOrRelease(&tables::$tbl, rawResult)")
          case _ => ("int", "0")
        }
        val fieldName =
          messageSpecs.find(_.className == resp).flatMap(_.fields.headOption.map(_.name)).getOrElse(field.name)
        s"""            $cppRetType rawResult = receiver->$cFn($argList);
           |${paramPostlude.mkString("\n")}
           |            gen::$resp resp;
           |            resp.$fieldName = $assign;
           |            std::vector<std::uint8_t> respPayload(resp.encodedSize());
           |            resp.encodeInto(respPayload.data());
           |            sendResponseEnvelope(frame, "cef4j_renderer_resp", corrId, messageId,
           |                                  respPayload.data(), respPayload.size());""".stripMargin
    }

    val preludeBlock = if (paramPrelude.isEmpty) "" else paramPrelude.mkString("\n") + "\n"

    s"""        case $msgIdExpr: {
       |            auto req = gen::$req::decode(payload.data(), payload.size());
       |            ${f.cefStructName}* receiver = tables::$table.retain(req.self);
       |            if (!receiver) {
       |                sendReceiverGone(frame, corrId, messageId);
       |                return true;
       |            }
       |            cef_v8_context_t* rawCtx = frame->get_v8_context(frame);
       |            ScopedV8Context v8ctx(rawCtx);
       |            if (!v8ctx.entered()) {
       |                auto* recvBase = reinterpret_cast<cef_base_ref_counted_t*>(receiver);
       |                recvBase->release(recvBase);
       |                sendReceiverGone(frame, corrId, messageId);
       |                return true;
       |            }
       |$preludeBlock            $callAndRespond
       |            auto* recvBase = reinterpret_cast<cef_base_ref_counted_t*>(receiver);
       |            recvBase->release(recvBase);
       |            return true;
       |        }""".stripMargin
  }
}
