package net.kurobako.cef4j.codegen.ipc

object JavaEmitter {

  def emit(spec: MessageSpec): String = {
    val pkg          = spec.packageName
    val cls          = spec.className
    val importsBlock = renderImports(spec)
    val fields       = renderFields(spec)
    val ctor         = renderConstructor(spec)
    val access       = renderAccessors(spec)
    val sizeFn       = renderEncodedSize(spec)
    val encFn        = renderEncodeInto(spec)
    val decFn        = renderDecoder(spec)

    s"""// Generated by net.kurobako.cef4j.codegen.ipc — do not edit by hand.
       |package $pkg;
       |
       |$importsBlock
       |
       |public final class $cls implements CefMessageView, CefMessageEncoder {
       |
       |    public static final int MESSAGE_ID = ${spec.messageId};
       |
       |$fields
       |
       |$ctor
       |
       |$access
       |
       |    @Override
       |    public int messageId() {
       |        return MESSAGE_ID;
       |    }
       |
       |$sizeFn
       |
       |$encFn
       |
       |$decFn
       |}
       |""".stripMargin
  }

  private def renderImports(spec: MessageSpec): String = {
    val needsString = spec.fields.exists(f => f.ty == FieldType.Utf8String || f.ty == FieldType.StringList)
    val needsHandle = spec.fields.exists(_.ty == FieldType.RemoteHandle)
    (
      List("import java.nio.ByteBuffer;", "import java.nio.ByteOrder;") ++
        Option.when(needsString)("import java.nio.charset.StandardCharsets;") ++
        List(
          "import javax.annotation.Nonnull;",
          "import net.kurobako.cef4j.ipc.session.CefMessageDecoder;",
          "import net.kurobako.cef4j.ipc.session.CefMessageEncoder;",
          "import net.kurobako.cef4j.ipc.session.CefMessageView;"
        ) ++
        Option.when(needsHandle)("import net.kurobako.cef4j.ipc.session.RemoteHandle;")
    ).mkString("\n")
  }

  private def javaType(ty: FieldType): String = ty match {
    case FieldType.I32                 => "int"
    case FieldType.I64                 => "long"
    case FieldType.Bool                => "boolean"
    case FieldType.Utf8String          => "String"
    case FieldType.Bytes               => "byte[]"
    case FieldType.StringList          => "String[]"
    case FieldType.RemoteHandle        => "RemoteHandle"
    case FieldType.DataStruct(cefName) => SpecDeriver.cefStructToClassName(cefName)
  }

  private def constructorParam(field: FieldSpec): String =
    field.ty match {
      case FieldType.Utf8String | FieldType.Bytes | FieldType.StringList | FieldType.RemoteHandle |
          FieldType.DataStruct(_) =>
        s"@Nonnull ${javaType(field.ty)} ${field.name}"
      case _ => s"${javaType(field.ty)} ${field.name}"
    }

  private def renderFields(spec: MessageSpec): String =
    spec.fields.flatMap { f =>
      f.ty match {
        case FieldType.Utf8String =>
          List(s"    private final String ${f.name};", s"    private final byte[] ${f.name}Bytes;")
        case _ =>
          List(s"    private final ${javaType(f.ty)} ${f.name};")
      }
    }.mkString("\n")

  private def renderConstructor(spec: MessageSpec): String = {
    val params = spec.fields.map(constructorParam).mkString(", ")
    val body   = spec.fields.flatMap { f =>
      f.ty match {
        case FieldType.Utf8String =>
          List(
            s"        this.${f.name} = ${f.name};",
            s"        this.${f.name}Bytes = ${f.name}.getBytes(StandardCharsets.UTF_8);"
          )
        case _ =>
          List(s"        this.${f.name} = ${f.name};")
      }
    }.mkString("\n")
    s"""    public ${spec.className}($params) {
       |$body
       |    }""".stripMargin
  }

  private def renderAccessors(spec: MessageSpec): String =
    spec.fields.map { f =>
      val ret = javaType(f.ty)
      f.ty match {
        case FieldType.Utf8String | FieldType.Bytes | FieldType.StringList | FieldType.RemoteHandle |
            FieldType.DataStruct(_) =>
          s"""    @Nonnull
             |    public $ret ${f.name}() {
             |        return ${f.name};
             |    }""".stripMargin
        case _ =>
          s"""    public $ret ${f.name}() {
             |        return ${f.name};
             |    }""".stripMargin
      }
    }.mkString("\n\n")

  private def fixedSize(ty: FieldType): Int = ty match {
    case FieldType.I32                          => 4
    case FieldType.I64                          => 8
    case FieldType.Bool                         => 1
    case FieldType.Utf8String | FieldType.Bytes => 4 // length prefix only; payload added at runtime
    case FieldType.StringList                   => 4 // count prefix only; per-string payloads added at runtime
    case FieldType.RemoteHandle                 => 4
    case FieldType.DataStruct(_)                => 0 // size is fully variable; comes from variableLengthExpr
  }

  private def variableLengthExpr(field: FieldSpec): Option[String] = field.ty match {
    case FieldType.Utf8String => Some(s"${field.name}Bytes.length")
    case FieldType.Bytes      => Some(s"${field.name}.length")
    case FieldType.StringList =>
      Some(
        s"java.util.Arrays.stream(${field.name}).mapToInt(__s -> 4 + __s.getBytes(StandardCharsets.UTF_8).length).sum()"
      )
    case FieldType.DataStruct(_) => Some(s"${field.name}.encodedSize()")
    case _                       => None
  }

  private def renderEncodedSize(spec: MessageSpec): String = {
    val fixed    = spec.fields.map(f => fixedSize(f.ty)).sum
    val variable = spec.fields.flatMap(variableLengthExpr).mkString(" + ")
    val expr     = if (variable.isEmpty) s"$fixed" else s"$fixed + $variable"
    s"""    @Override
       |    public int encodedSize() {
       |        return $expr;
       |    }""".stripMargin
  }

  private def renderEncodeInto(spec: MessageSpec): String = {
    val writes = spec.fields.flatMap(encodeWrite).mkString("\n")
    s"""    @Override
       |    public void encodeInto(@Nonnull ByteBuffer __dst) {
       |        ByteOrder originalOrder = __dst.order();
       |        try {
       |            __dst.order(ByteOrder.LITTLE_ENDIAN);
       |$writes
       |        } finally {
       |            __dst.order(originalOrder);
       |        }
       |    }""".stripMargin
  }

  private def encodeWrite(field: FieldSpec): List[String] = field.ty match {
    case FieldType.I32        => List(s"            __dst.putInt(${field.name});")
    case FieldType.I64        => List(s"            __dst.putLong(${field.name});")
    case FieldType.Bool       => List(s"            __dst.put((byte) (${field.name} ? 1 : 0));")
    case FieldType.Utf8String =>
      List(
        s"            __dst.putInt(${field.name}Bytes.length);",
        s"            __dst.put(${field.name}Bytes);"
      )
    case FieldType.Bytes =>
      List(
        s"            __dst.putInt(${field.name}.length);",
        s"            __dst.put(${field.name});"
      )
    case FieldType.StringList =>
      List(
        s"            __dst.putInt(${field.name}.length);",
        s"            for (String __s : ${field.name}) {",
        s"                byte[] __b = __s.getBytes(StandardCharsets.UTF_8);",
        s"                __dst.putInt(__b.length);",
        s"                __dst.put(__b);",
        s"            }"
      )
    case FieldType.RemoteHandle  => List(s"            __dst.putInt(${field.name}.id());")
    case FieldType.DataStruct(_) =>
      List(s"            ${field.name}.encodeInto(__dst);")
  }

  private def renderDecoder(spec: MessageSpec): String = {
    val reads = spec.fields.flatMap(decodeRead).mkString("\n")
    val args  = spec.fields.map(_.name).mkString(", ")
    s"""    public static final CefMessageDecoder<${spec.className}> DECODER = payload -> {
       |        ByteBuffer __buf = payload.duplicate();
       |        __buf.order(ByteOrder.LITTLE_ENDIAN);
       |$reads
       |        return new ${spec.className}($args);
       |    };""".stripMargin
  }

  private def decodeRead(field: FieldSpec): List[String] = field.ty match {
    case FieldType.I32        => List(s"        int ${field.name} = __buf.getInt();")
    case FieldType.I64        => List(s"        long ${field.name} = __buf.getLong();")
    case FieldType.Bool       => List(s"        boolean ${field.name} = __buf.get() != 0;")
    case FieldType.Utf8String =>
      List(
        s"        int ${field.name}Len = __buf.getInt();",
        s"        byte[] ${field.name}Buf = new byte[${field.name}Len];",
        s"        __buf.get(${field.name}Buf);",
        s"        String ${field.name} = new String(${field.name}Buf, StandardCharsets.UTF_8);"
      )
    case FieldType.Bytes =>
      List(
        s"        int ${field.name}Len = __buf.getInt();",
        s"        byte[] ${field.name} = new byte[${field.name}Len];",
        s"        __buf.get(${field.name});"
      )
    case FieldType.StringList =>
      List(
        s"        int ${field.name}Count = __buf.getInt();",
        s"        String[] ${field.name} = new String[${field.name}Count];",
        s"        for (int __i = 0; __i < ${field.name}Count; __i++) {",
        s"            int __slen = __buf.getInt();",
        s"            byte[] __sb = new byte[__slen];",
        s"            __buf.get(__sb);",
        s"            ${field.name}[__i] = new String(__sb, StandardCharsets.UTF_8);",
        s"        }"
      )
    case FieldType.RemoteHandle =>
      List(s"        RemoteHandle ${field.name} = new RemoteHandle(__buf.getInt());")
    case FieldType.DataStruct(cefName) =>
      val cls = SpecDeriver.cefStructToClassName(cefName)
      List(s"        $cls ${field.name} = $cls.decode(__buf);")
  }
}
