package net.kurobako.cef4j.codegen.ipc

object JavaHandlerEmitter {

  def emit(spec: HandlerSpec): String = {
    val pkg     = spec.packageName
    val cls     = spec.className
    val methods = spec.methods.map(renderInterfaceMethod).mkString("\n\n")
    val ons     = spec.methods.flatMap(renderRegistration).mkString(",\n")

    s"""// Generated by net.kurobako.cef4j.codegen.ipc — do not edit by hand.
       |package $pkg;
       |
       |import javax.annotation.Nullable;
       |import net.kurobako.cef4j.ipc.session.CefSession;
       |
       |/**
       | * Typed handler interface for {@code ${spec.cefStructName}}. Each method maps to a callback CEF would
       | * fire on this struct; default empty bodies let implementers override only the events they want.
       | *
       | * <p>Use {@link #register(CefSession, $cls)} to bind every method to its corresponding wire event in
       | * one step. Close the returned registration to unsubscribe every method.
       | */
       |@SuppressWarnings("NullableForbidden")
       |public interface $cls {
       |
       |$methods
       |
       |    /** Registers {@code handler} for every event this interface declares. */
       |    static CefSession.HandlerRegistration register(CefSession session, $cls handler) {
       |        return CefSession.HandlerRegistration.combine(
       |$ons);
       |    }
       |}
       |""".stripMargin
  }

  private def renderInterfaceMethod(m: HandlerMethod): String = {
    val params = m.params.map(p => s"${javaParamType(p.ty)} ${p.name}").mkString(", ")
    m.returnType match {
      case None =>
        val doc = methodDoc(m, s"Mirrors the {@code ${snakeOf(m.methodName)}} callback on the CEF struct.")
        s"""$doc    default void ${m.methodName}($params) {}""".stripMargin
      case Some(FieldType.Bool) =>
        // Null means no JVM opinion and maps to CEF's false default.
        val doc = methodDoc(
          m,
          s"Mirrors the {@code ${snakeOf(m.methodName)}} callback. A null result selects CEF's default behavior."
        )
        s"""$doc    @Nullable
           |    default Boolean ${m.methodName}($params) { return null; }""".stripMargin
      case Some(_) =>
        s"""    default void ${m.methodName}($params) {}""".stripMargin
    }
  }

  private def methodDoc(m: HandlerMethod, fallback: String): String =
    if (m.javadoc.nonEmpty) m.javadoc.linesIterator.mkString("\n") + "\n"
    else s"""    /** $fallback */
            |""".stripMargin

  private def renderRegistration(m: HandlerMethod): Option[String] = {
    val args = m.params.map(p => s"ev.${p.name}()").mkString(", ")
    m.returnType match {
      case None =>
        val subscription =
          if (m.eventClassName == "LifeSpanHandlerOnAfterCreatedEvent") "onLatest" else "on"
        Some(s"""                session.$subscription(${m.eventClassName}.MESSAGE_ID, ${m.eventClassName}.DECODER,
                |                        ev -> handler.${m.methodName}($args))""".stripMargin)
      case Some(FieldType.Bool) =>
        val respCls = m.responseClassName.getOrElse(m.eventClassName + "Response")
        Some(s"""                session.intercept(${m.eventClassName}.MESSAGE_ID, ${m.eventClassName}.DECODER, ev -> {
                |                    Boolean answer = handler.${m.methodName}($args);
                |                    return new $respCls(answer != null && answer.booleanValue());
                |                })""".stripMargin)
      case Some(_) =>
        None
    }
  }

  private def javaParamType(ty: FieldType): String = ty match {
    case FieldType.I32                 => "int"
    case FieldType.I64                 => "long"
    case FieldType.Bool                => "boolean"
    case FieldType.Utf8String          => "String"
    case FieldType.Bytes               => "byte[]"
    case FieldType.StringList          => "String[]"
    case FieldType.RemoteHandle        => "net.kurobako.cef4j.ipc.session.RemoteHandle"
    case FieldType.DataStruct(cefName) => SpecDeriver.cefStructToClassName(cefName)
  }

  private def snakeOf(camel: String): String = camel.zipWithIndex.flatMap { case (c, index) =>
    if (c.isUpper && index > 0) s"_${c.toLower}" else c.toLower.toString
  }.mkString
}
