package net.kurobako.cef4j.codegen.ipc

object JavaJvmVisitorEmitter {

  def emit(spec: JvmVisitorSpec): String = {
    val pkg        = spec.packageName
    val cls        = spec.className
    val event      = spec.eventClassName
    val params     = spec.params.map(p => s"${javaParamType(p.ty)} ${p.name}").mkString(", ")
    val callArgs   = spec.params.map(p => s"ev.${p.name}()").mkString(", ")
    val methodName = spec.methodName

    s"""// Generated by net.kurobako.cef4j.codegen.ipc — do not edit by hand.
       |package $pkg;
       |
       |import net.kurobako.cef4j.ipc.session.CefSession;
       |import net.kurobako.cef4j.ipc.session.JvmCallbackTable;
       |
       |/**
       | * Typed interface for {@code ${spec.cefStructName}}, a JVM-owned CEF visitor. JVM provides the implementation,
       | * passes a callbackId minted from a {@link JvmCallbackTable} as the visitor handle to a CEF method, and the
       | * runtime server synthesises a real {@code ${spec.cefStructName}} that routes the callback back to the JVM.
       | */
       |@FunctionalInterface
       |public interface $cls {
       |
       |${
        if (spec.javadoc.nonEmpty) spec.javadoc
        else s"    /** Mirrors the {@code ${spec.cefMethodName}} callback on the CEF struct. */"
      }
       |    void $methodName($params);
       |
       |    /**
       |     * Wires inbound {@link $event} frames into the supplied {@code table} so each visitor invocation
       |     * dispatches to the {@code $cls} registered under that callbackId. Call once per session.
       |     */
       |    static void route(CefSession session, JvmCallbackTable<$cls> table) {
       |        session.on($event.MESSAGE_ID, $event.DECODER, ev -> {
       |            $cls v = table.lookup(ev.callbackId());
       |            if (v != null) v.$methodName($callArgs);
       |        });
       |    }
       |}
       |""".stripMargin
  }

  private def javaParamType(ty: FieldType): String = ty match {
    case FieldType.I32                 => "int"
    case FieldType.I64                 => "long"
    case FieldType.Bool                => "boolean"
    case FieldType.Utf8String          => "String"
    case FieldType.Bytes               => "byte[]"
    case FieldType.StringList          => "String[]"
    case FieldType.RemoteHandle        => "net.kurobako.cef4j.ipc.session.RemoteHandle"
    case FieldType.DataStruct(cefName) => SpecDeriver.cefStructToClassName(cefName)
  }
}
