package net.kurobako.cef4j.codegen.ipc

/** Emits a Java interface per CEF HandlerStruct (e.g. `cef_load_handler_t` → `CefLoadHandler`). The interface exposes
  * one default-`{}` method per callback so implementers only override what they care about, plus a static
  * `register(CefSession, Handler)` that wires `session.on(...)` for every event the handler covers.
  *
  * Helper-side wiring (setting these handlers on a `CefClient` and forwarding C callbacks to IPC events) is a separate
  * concern; these interfaces are useful even before that lands as a typed dispatch surface for any future helper code
  * that emits the corresponding events.
  */
object JavaHandlerEmitter {

  def emit(spec: HandlerSpec): String = {
    val pkg     = spec.packageName
    val cls     = spec.className
    val methods = spec.methods.map(renderInterfaceMethod).mkString("\n\n")
    val ons     = spec.methods.map(renderRegisterCall).mkString("\n")

    s"""// Generated by net.kurobako.cef4j.codegen.ipc — do not edit by hand.
       |package $pkg;
       |
       |import javax.annotation.Nullable;
       |import net.kurobako.cef4j.ipc.session.CefSession;
       |
       |/**
       | * Typed handler interface for {@code ${spec.cefStructName}}. Each method maps to a callback CEF would
       | * fire on this struct; default empty bodies let implementers override only the events they want.
       | *
       | * <p>Use {@link #register(CefSession, $cls)} to bind every method to its corresponding wire event in
       | * one step. Subscriptions stay live until the session closes.
       | */
       |public interface $cls {
       |
       |$methods
       |
       |    /** Registers {@code handler} for every event this interface declares. */
       |    static void register(CefSession session, $cls handler) {
       |$ons
       |    }
       |}
       |""".stripMargin
  }

  private def renderInterfaceMethod(m: HandlerMethod): String = {
    val params = m.params.map(p => s"${javaParamType(p.ty)} ${p.name}").mkString(", ")
    m.returnType match {
      case None =>
        s"""    /** Mirrors the {@code ${snakeOf(m.methodName)}} callback on the CEF struct. */
           |    default void ${m.methodName}($params) {}""".stripMargin
      case Some(FieldType.Bool) =>
        // Returns Boolean (boxed) so a `null` answer can mean "no opinion → don't bind"; falls through to
        // CEF's default-zero behavior. Otherwise true→1 (block popup, suppress dialog, cancel navigation).
        s"""    /** Mirrors the {@code ${snakeOf(m.methodName)}} callback. Return {@code null} or omit override
           |      * for CEF's default behavior (treated as 0); return {@link Boolean#TRUE}/{@link Boolean#FALSE} to
           |      * supply the int return value the helper hands back to CEF. */
           |    @Nullable
           |    default Boolean ${m.methodName}($params) { return null; }""".stripMargin
      case Some(_) =>
        // SpecDeriver currently only emits Bool returns, but keep a safe default-void in case the model
        // grows other return shapes (e.g. int64_t for stream-read sizes).
        s"""    default void ${m.methodName}($params) {}""".stripMargin
    }
  }

  private def renderRegisterCall(m: HandlerMethod): String = {
    val args = m.params.map(p => s"ev.${p.name}()").mkString(", ")
    m.returnType match {
      case None =>
        s"""        session.on(${m.eventClassName}.MESSAGE_ID, ${m.eventClassName}.DECODER,
           |                ev -> handler.${m.methodName}($args));""".stripMargin
      case Some(FieldType.Bool) =>
        // Non-void: bind via session.intercept(). The handler returns Boolean — null means default (0)
        // and is encoded as a Response with result=false; non-null becomes the explicit answer.
        val respCls = m.responseClassName.getOrElse(m.eventClassName + "Response")
        s"""        session.intercept(${m.eventClassName}.MESSAGE_ID, ${m.eventClassName}.DECODER, ev -> {
           |            Boolean answer = handler.${m.methodName}($args);
           |            return new $respCls(answer != null && answer.booleanValue());
           |        });""".stripMargin
      case Some(_) =>
        s"""        // ${m.methodName}: skipped (unsupported return type)""".stripMargin
    }
  }

  private def javaParamType(ty: FieldType): String = ty match {
    case FieldType.I32                 => "int"
    case FieldType.I64                 => "long"
    case FieldType.Bool                => "boolean"
    case FieldType.Utf8String          => "String"
    case FieldType.Bytes               => "byte[]"
    case FieldType.StringList          => "String[]"
    case FieldType.RemoteHandle        => "net.kurobako.cef4j.ipc.session.RemoteHandle"
    case FieldType.DataStruct(cefName) => SpecDeriver.cefStructToClassName(cefName)
  }

  private def snakeOf(camel: String): String = {
    val sb = new StringBuilder
    camel.zipWithIndex.foreach { case (c, i) =>
      if (c.isUpper && i > 0) sb.append('_')
      sb.append(c.toLower)
    }
    sb.toString
  }
}
