package net.kurobako.cef4j.codegen.ipc

/** Emits a Java facade class per CEF object: holds a `RemoteHandle` + `CefSession`, exposes typed methods that dispatch
  * through `session.request`. Companion to `JavaEmitter`, which produces the wire-format types the facade methods
  * reference.
  *
  * Example output for `cef_browser_t::can_go_back() -> int`:
  * {{{
  *   public CompletableFuture<Boolean> canGoBack() {
  *       return session.request(new BrowserCanGoBackRequest(handle), BrowserCanGoBackResponse.DECODER)
  *               .thenApply(BrowserCanGoBackResponse::result);
  *   }
  * }}}
  *
  * Void methods return `CompletableFuture<Void>` (the empty Response is mapped to `null`).
  */
object JavaFacadeEmitter {

  /** {@code facadeByCefStruct} maps CEF struct names (e.g. `"cef_frame_t"`) to the JVM facade class (e.g. `"Frame"`) so
    * methods returning a RemoteHandle can be typed as the wrapper.
    */
  def emit(
      spec: FacadeSpec,
      facadeByCefStruct: Map[String, String] = Map.empty,
      affinityByCefStruct: Map[String, ProcessAffinity] = Map.empty
  ): String = {
    val pkg          = spec.packageName
    val cls          = spec.className
    val importsBlock = renderImports(spec)
    val isRenderer   = spec.affinity == ProcessAffinity.Renderer
    val ctor         = renderConstructor(spec)
    val methods = spec.methods.map(m => renderMethod(spec, m, facadeByCefStruct, affinityByCefStruct)).mkString("\n\n")
    val close   = renderClose(spec)
    val frameField    = if (isRenderer) "    private final RemoteHandle frame;\n" else ""
    val frameAccessor =
      if (isRenderer)
        """
          |    /** The frame whose V8 context this handle lives in. Renderer-side dispatch enters this frame's
          |      * V8 context before invoking methods on the receiver. */
          |    @Nonnull
          |    public RemoteHandle frame() {
          |        return frame;
          |    }""".stripMargin
      else ""

    s"""// Generated by net.kurobako.cef4j.codegen.ipc — do not edit by hand.
       |package $pkg;
       |
       |$importsBlock
       |
       |/**
       | * Typed facade for {@code ${spec.cefStructName}}, dispatching through a {@link CefSession}.
       | * Each instance is a thin wrapper around a {@link RemoteHandle} that points at a runtime-server-side
       | * ref-counted CEF object.
       | */
       |public final class $cls {
       |
       |    private final CefSession session;
       |$frameField    private final RemoteHandle handle;
       |
       |$ctor
       |
       |    @Nonnull
       |    public RemoteHandle handle() {
       |        return handle;
       |    }
       |$frameAccessor
       |
       |$close
       |
       |$methods
       |}
       |""".stripMargin
  }

  /** Sends a `ReleaseHandleRequest` keyed by the facade's CEF struct name; the runtime server's `dispatchRelease`
    * routes to the matching `tables::X.release(id)`. After this future completes, the runtime-server-side handle is
    * gone and any subsequent method call on this facade will fail with "no receiver". Caller is responsible for not
    * double-releasing.
    *
    * Named `releaseHandle()` rather than `close()` because some CEF facades (`cef_window_t`, `cef_xml_reader_t`,
    * `cef_zip_reader_t`) already define a `close()` C-API method and we mustn't shadow them.
    */
  private def renderClose(spec: FacadeSpec): String =
    if (spec.affinity == ProcessAffinity.Renderer)
      // Renderer-affinity handles live in the renderer subprocess's `tables::X`, not the browser's. Plain
      // ReleaseHandleRequest dispatches in the browser and would silently no-op. RendererReleaseHandleRequest
      // carries the frame so the browser-side relay ships it to the right renderer; the renderer-side
      // runtime server turns it into a dispatchRelease against its own table state.
      s"""    /** Releases the runtime-server-side handle this facade points at. Routed via the renderer relay since
         |      * ${spec.cefStructName} only exists in the renderer subprocess's table state. */
         |    public java.util.concurrent.CompletableFuture<Void> releaseHandle() {
         |        return session
         |            .request(
         |                new RendererReleaseHandleRequest(frame, handle, "${spec.cefStructName}"),
         |                RendererReleaseHandleResponse.DECODER)
         |            .thenApply(r -> null);
         |    }""".stripMargin
    else
      s"""    /** Releases the runtime-server-side handle this facade points at. Subsequent method calls on this instance
         |      * will fail with an empty / null-receiver response. */
         |    public java.util.concurrent.CompletableFuture<Void> releaseHandle() {
         |        return session
         |            .request(new ReleaseHandleRequest(handle, "${spec.cefStructName}"), ReleaseHandleResponse.DECODER)
         |            .thenApply(r -> null);
         |    }""".stripMargin

  private def snakeOf(camel: String): String = {
    val sb = new StringBuilder
    camel.zipWithIndex.foreach { case (c, i) =>
      if (c.isUpper && i > 0) sb.append('_')
      sb.append(c.toLower)
    }
    sb.toString
  }

  private def renderImports(spec: FacadeSpec): String = {
    val sb = List.newBuilder[String]
    sb += "import java.util.concurrent.CompletableFuture;"
    sb += "import javax.annotation.Nonnull;"
    sb += "import net.kurobako.cef4j.ipc.session.CefSession;"
    sb += "import net.kurobako.cef4j.ipc.session.RemoteHandle;"
    // Each method references a generated Request + Response in the same package; no extra imports needed.
    sb.result().mkString("\n")
  }

  private def renderConstructor(spec: FacadeSpec): String =
    if (spec.affinity == ProcessAffinity.Renderer)
      s"""    public ${spec.className}(@Nonnull CefSession session, @Nonnull RemoteHandle frame, @Nonnull RemoteHandle handle) {
         |        this.session = session;
         |        this.frame = frame;
         |        this.handle = handle;
         |    }""".stripMargin
    else
      s"""    public ${spec.className}(@Nonnull CefSession session, @Nonnull RemoteHandle handle) {
         |        this.session = session;
         |        this.handle = handle;
         |    }""".stripMargin

  private def renderMethod(
      facade: FacadeSpec,
      m: FacadeMethod,
      facadeByCefStruct: Map[String, String],
      affinityByCefStruct: Map[String, ProcessAffinity]
  ): String = {
    // Renderer-affinity Requests start with `frame: RemoteHandle` ahead of `self`. The facade injects
    // its constructor-stored frame transparently — the user-facing method signature is unchanged.
    val frameLead                  = if (facade.affinity == ProcessAffinity.Renderer) List("frame") else Nil
    val ctorArgs                   = (frameLead ++ ("handle" :: m.explicitParams.map(_.name))).mkString(", ")
    val (returnType, mapperSuffix) = m.resultField match {
      case None    => ("CompletableFuture<Void>", ".thenApply(r -> null)")
      case Some(f) =>
        f.ty match {
          case FieldType.RemoteHandle =>
            // If we know which facade wraps the result struct, return the typed wrapper instead of the bare
            // handle. The user gets a `CompletableFuture<Frame>` from `Browser.getMainFrame()` rather than
            // having to wrap manually, and the returned facade carries the same `session` for chained calls.
            m.handleStructByField.get("result").flatMap(facadeByCefStruct.get) match {
              case Some(facadeCls) =>
                // Decide what frame the child facade should carry, if it's renderer-affinity:
                //   - parent renderer  → propagate parent's `frame` field (same V8 context).
                //   - parent is `cef_frame_t` → the parent's own `handle` IS the frame.
                //   - any other browser parent returning a renderer child → no clean frame to attach.
                //     Skip the typed wrapper and return RemoteHandle so the user can construct manually.
                val childAffinity = m.handleStructByField
                  .get("result")
                  .flatMap(affinityByCefStruct.get)
                  .getOrElse(ProcessAffinity.Browser)
                val frameExprForChild: Option[String] =
                  if (childAffinity != ProcessAffinity.Renderer) None
                  else if (facade.affinity == ProcessAffinity.Renderer) Some("frame")
                  else if (facade.cefStructName == "cef_frame_t") Some("handle")
                  else None
                if (childAffinity == ProcessAffinity.Renderer && frameExprForChild.isEmpty) {
                  (s"CompletableFuture<RemoteHandle>", s".thenApply(${m.responseClassName}::${f.name})")
                } else {
                  val childCtor = frameExprForChild match {
                    case Some(frameExpr) => s"new $facadeCls(session, $frameExpr, __h)"
                    case None            => s"new $facadeCls(session, __h)"
                  }
                  (
                    s"CompletableFuture<$facadeCls>",
                    s".thenApply(${m.responseClassName}::${f.name})\n" +
                      s"            .thenApply(__h -> $childCtor)"
                  )
                }
              case None =>
                (s"CompletableFuture<RemoteHandle>", s".thenApply(${m.responseClassName}::${f.name})")
            }
          case _ =>
            (s"CompletableFuture<${boxedType(f.ty)}>", s".thenApply(${m.responseClassName}::${f.name})")
        }
    }
    val paramAnnots = m.explicitParams.map { p =>
      p.ty match {
        case FieldType.Utf8String | FieldType.Bytes | FieldType.RemoteHandle =>
          s"@Nonnull ${javaParamType(p.ty)} ${p.name}"
        case _ => s"${javaParamType(p.ty)} ${p.name}"
      }
    }.mkString(", ")
    val methodDoc =
      if (m.javadoc.nonEmpty) m.javadoc.linesIterator.mkString("\n") + "\n"
      else s"""    /** Dispatches {@code ${m.cefMethodName}} to the runtime server. */
              |""".stripMargin
    s"""$methodDoc    public $returnType ${m.methodName}($paramAnnots) {
       |        return session
       |            .request(new ${m.requestClassName}($ctorArgs), ${m.responseClassName}.DECODER)
       |            $mapperSuffix;
       |    }""".stripMargin
  }

  private def javaParamType(ty: FieldType): String = ty match {
    case FieldType.I32                 => "int"
    case FieldType.I64                 => "long"
    case FieldType.Bool                => "boolean"
    case FieldType.Utf8String          => "String"
    case FieldType.Bytes               => "byte[]"
    case FieldType.StringList          => "String[]"
    case FieldType.RemoteHandle        => "RemoteHandle"
    case FieldType.DataStruct(cefName) => SpecDeriver.cefStructToClassName(cefName)
  }

  private def boxedType(ty: FieldType): String = ty match {
    case FieldType.I32                 => "Integer"
    case FieldType.I64                 => "Long"
    case FieldType.Bool                => "Boolean"
    case FieldType.Utf8String          => "String"
    case FieldType.Bytes               => "byte[]"
    case FieldType.StringList          => "String[]"
    case FieldType.RemoteHandle        => "RemoteHandle"
    case FieldType.DataStruct(cefName) => SpecDeriver.cefStructToClassName(cefName)
  }
}
