package net.kurobako.cef4j.codegen.ipc

object JavaFacadeEmitter {

  def emit(
      spec: FacadeSpec,
      facadeByCefStruct: Map[String, String] = Map.empty,
      affinityByCefStruct: Map[String, ProcessAffinity] = Map.empty
  ): String = {
    val pkg          = spec.packageName
    val cls          = spec.className
    val importsBlock = renderImports
    val isRenderer   = spec.affinity == ProcessAffinity.Renderer
    val ctor         = renderConstructor(spec)
    val methods = spec.methods.map(m => renderMethod(spec, m, facadeByCefStruct, affinityByCefStruct)).mkString("\n\n")
    val close   = renderClose(spec)
    val frameField    = if (isRenderer) "    private final RemoteHandle frame;\n" else ""
    val frameAccessor =
      if (isRenderer)
        """
          |    /** The frame whose V8 context this handle lives in. Renderer-side dispatch enters this frame's
          |      * V8 context before invoking methods on the receiver. */
          |    @Nonnull
          |    public RemoteHandle frame() {
          |        return frame;
          |    }""".stripMargin
      else ""

    s"""// Generated by net.kurobako.cef4j.codegen.ipc — do not edit by hand.
       |package $pkg;
       |
       |$importsBlock
       |
       |/**
       | * Typed facade for {@code ${spec.cefStructName}}, dispatching through a {@link CefSession}.
       | * Each instance is a thin wrapper around a {@link RemoteHandle} that points at a runtime-server-side
       | * ref-counted CEF object.
       | */
       |public final class $cls {
       |
       |    private final CefSession session;
       |$frameField    private final RemoteHandle handle;
       |
       |$ctor
       |
       |    @Nonnull
       |    public RemoteHandle handle() {
       |        return handle;
       |    }
       |$frameAccessor
       |
       |$close
       |
       |$methods
       |}
       |""".stripMargin
  }

  private def renderClose(spec: FacadeSpec): String =
    if (spec.affinity == ProcessAffinity.Renderer)
      // Renderer-owned handles must be released through their frame.
      s"""    /** Releases the runtime-server-side handle this facade points at. Routed via the renderer relay since
         |      * ${spec.cefStructName} only exists in the renderer subprocess's table state. */
         |    public java.util.concurrent.CompletableFuture<Void> releaseHandle() {
         |        return CefFutures.map(
         |            session.request(
         |                new RendererReleaseHandleRequest(frame, handle, "${spec.cefStructName}"),
         |                RendererReleaseHandleResponse.DECODER),
         |            r -> null);
         |    }""".stripMargin
    else
      s"""    /** Releases the runtime-server-side handle this facade points at. Subsequent method calls on this instance
         |      * will fail with an empty / null-receiver response. */
         |    public java.util.concurrent.CompletableFuture<Void> releaseHandle() {
         |        return CefFutures.map(
         |            session.request(
         |                new ReleaseHandleRequest(handle, "${spec.cefStructName}"), ReleaseHandleResponse.DECODER),
         |            r -> null);
         |    }""".stripMargin

  private def renderImports: String = List(
    "import java.util.concurrent.CompletableFuture;",
    "import javax.annotation.Nonnull;",
    "import net.kurobako.cef4j.ipc.session.CefFutures;",
    "import net.kurobako.cef4j.ipc.session.CefSession;",
    "import net.kurobako.cef4j.ipc.session.RemoteHandle;"
  ).mkString("\n")

  private def renderConstructor(spec: FacadeSpec): String =
    if (spec.affinity == ProcessAffinity.Renderer)
      s"""    public ${spec.className}(@Nonnull CefSession session, @Nonnull RemoteHandle frame, @Nonnull RemoteHandle handle) {
         |        this.session = session;
         |        this.frame = frame;
         |        this.handle = handle;
         |    }""".stripMargin
    else
      s"""    public ${spec.className}(@Nonnull CefSession session, @Nonnull RemoteHandle handle) {
         |        this.session = session;
         |        this.handle = handle;
         |    }""".stripMargin

  private def renderMethod(
      facade: FacadeSpec,
      m: FacadeMethod,
      facadeByCefStruct: Map[String, String],
      affinityByCefStruct: Map[String, ProcessAffinity]
  ): String = {
    val frameLead            = if (facade.affinity == ProcessAffinity.Renderer) List("frame") else Nil
    val ctorArgs             = (frameLead ++ ("handle" :: m.explicitParams.map(_.name))).mkString(", ")
    val (returnType, mapper) = m.resultField match {
      case None    => ("CompletableFuture<Void>", "r -> null")
      case Some(f) =>
        f.ty match {
          case FieldType.RemoteHandle =>
            m.handleStructByField.get("result").flatMap(facadeByCefStruct.get) match {
              case Some(facadeCls) =>
                val childAffinity = m.handleStructByField
                  .get("result")
                  .flatMap(affinityByCefStruct.get)
                  .getOrElse(ProcessAffinity.Browser)
                val frameExprForChild: Option[String] =
                  if (childAffinity != ProcessAffinity.Renderer) None
                  else if (facade.affinity == ProcessAffinity.Renderer) Some("frame")
                  else if (facade.cefStructName == "cef_frame_t") Some("handle")
                  else None
                if (childAffinity == ProcessAffinity.Renderer && frameExprForChild.isEmpty) {
                  (s"CompletableFuture<RemoteHandle>", s"${m.responseClassName}::${f.name}")
                } else {
                  val childCtor = frameExprForChild match {
                    case Some(frameExpr) => s"new $facadeCls(session, $frameExpr, __r.${f.name}())"
                    case None            => s"new $facadeCls(session, __r.${f.name}())"
                  }
                  (s"CompletableFuture<$facadeCls>", s"__r -> $childCtor")
                }
              case None =>
                (s"CompletableFuture<RemoteHandle>", s"${m.responseClassName}::${f.name}")
            }
          case _ =>
            (s"CompletableFuture<${boxedType(f.ty)}>", s"${m.responseClassName}::${f.name}")
        }
    }
    val paramAnnots = m.explicitParams.map { p =>
      p.ty match {
        case FieldType.Utf8String | FieldType.Bytes | FieldType.RemoteHandle =>
          s"@Nonnull ${javaParamType(p.ty)} ${p.name}"
        case _ => s"${javaParamType(p.ty)} ${p.name}"
      }
    }.mkString(", ")
    val methodDoc =
      if (m.javadoc.nonEmpty) m.javadoc.linesIterator.mkString("\n") + "\n"
      else s"""    /** Dispatches {@code ${m.cefMethodName}} to the runtime server. */
              |""".stripMargin
    s"""$methodDoc    public $returnType ${m.methodName}($paramAnnots) {
       |        return CefFutures.map(
       |            session.request(new ${m.requestClassName}($ctorArgs), ${m.responseClassName}.DECODER),
       |            $mapper);
       |    }""".stripMargin
  }

  private def javaParamType(ty: FieldType): String = ty match {
    case FieldType.I32                 => "int"
    case FieldType.I64                 => "long"
    case FieldType.Bool                => "boolean"
    case FieldType.Utf8String          => "String"
    case FieldType.Bytes               => "byte[]"
    case FieldType.StringList          => "String[]"
    case FieldType.RemoteHandle        => "RemoteHandle"
    case FieldType.DataStruct(cefName) => SpecDeriver.cefStructToClassName(cefName)
  }

  private def boxedType(ty: FieldType): String = ty match {
    case FieldType.I32                 => "Integer"
    case FieldType.I64                 => "Long"
    case FieldType.Bool                => "Boolean"
    case FieldType.Utf8String          => "String"
    case FieldType.Bytes               => "byte[]"
    case FieldType.StringList          => "String[]"
    case FieldType.RemoteHandle        => "RemoteHandle"
    case FieldType.DataStruct(cefName) => SpecDeriver.cefStructToClassName(cefName)
  }
}
