package net.kurobako.cef4j.codegen.ipc

object JavaDataStructEmitter {

  def emit(spec: DataStructSpec): String = {
    val pkg          = spec.packageName
    val cls          = spec.className
    val importsBlock = renderImports
    val ctor         = renderCtor(spec)
    val getters      = spec.fields.map(renderGetter).mkString("\n\n")
    val sizeBody     = renderSizeBody(spec)
    val encodeBody   = renderEncodeBody(spec)
    val decodeBody   = renderDecodeBody(spec)
    val builder      = renderBuilder(spec)

    s"""// Generated by net.kurobako.cef4j.codegen.ipc — do not edit by hand.
       |package $pkg;
       |
       |$importsBlock
       |
       |/**
       | * Wire-format value type mirroring {@code ${spec.cefStructName}}. Fields are immutable; pass instances
       | * to facade methods (or factory requests) that take this struct. The dispatcher decodes them on the
       | * runtime-server side and fills the matching {@code ${spec.cefStructName}} before invoking CEF.
       | */
       |public final class $cls {
       |
       |${spec.fields.map(renderField).mkString("\n")}
       |
       |$ctor
       |
       |$getters
       |
       |    public int encodedSize() {
       |        return $sizeBody;
       |    }
       |
       |    public void encodeInto(@Nonnull ByteBuffer dst) {
       |        ByteOrder originalOrder = dst.order();
       |        try {
       |            dst.order(ByteOrder.LITTLE_ENDIAN);
       |$encodeBody
       |        } finally {
       |            dst.order(originalOrder);
       |        }
       |    }
       |
       |    /** Reads in place from {@code __buf}, advancing its position. Caller must have set
       |      * {@link ByteOrder#LITTLE_ENDIAN} on the buffer (the standalone {@code decode(payload)} entry point
       |      * below does that for you). For nested use inside a parent message's decoder the parent has already
       |      * configured the buffer.
       |      */
       |    public static $cls decode(@Nonnull ByteBuffer __buf) {
       |$decodeBody
       |        return new $cls(${spec.fields.map(_.name).mkString(", ")});
       |    }
       |
       |    public static Builder builder() {
       |        return new Builder();
       |    }
       |
       |$builder
       |}
       |""".stripMargin
  }

  private def renderBuilder(spec: DataStructSpec): String = {
    val cls     = spec.className
    val bFields =
      spec.fields.map(f => s"        private ${javaType(f.ty)} ${f.name} = ${defaultValue(f.ty)};").mkString("\n")
    val setters   = spec.fields.map(renderSetter).mkString("\n\n")
    val buildArgs = spec.fields.map(_.name).mkString(", ")
    s"""    /** Lombok-style builder. */
       |    public static final class Builder {
       |
       |$bFields
       |
       |$setters
       |
       |        public $cls build() {
       |            return new $cls($buildArgs);
       |        }
       |    }""".stripMargin
  }

  private def renderSetter(f: FieldSpec): String = {
    val annot = f.ty match {
      case FieldType.Utf8String | FieldType.Bytes | FieldType.RemoteHandle | FieldType.DataStruct(_) =>
        "@Nonnull "
      case _ => ""
    }
    s"""        public Builder ${f.name}($annot${javaType(f.ty)} ${f.name}) {
       |            this.${f.name} = ${f.name};
       |            return this;
       |        }""".stripMargin
  }

  private def defaultValue(ty: FieldType): String = ty match {
    case FieldType.I32           => "0"
    case FieldType.I64           => "0L"
    case FieldType.Bool          => "false"
    case FieldType.Utf8String    => "\"\""
    case FieldType.Bytes         => "new byte[0]"
    case FieldType.StringList    => "new String[0]" // unreachable; data structs don't carry StringLists
    case FieldType.RemoteHandle  => "net.kurobako.cef4j.ipc.session.RemoteHandle.NULL"
    case FieldType.DataStruct(_) => "null"          // builder forces explicit set; null reaches Nonnull-annotated ctor
  }

  private def renderImports: String =
    """import java.nio.ByteBuffer;
      |import java.nio.ByteOrder;
      |import java.nio.charset.StandardCharsets;
      |import javax.annotation.Nonnull;""".stripMargin

  private def renderField(f: FieldSpec): String =
    s"    private final ${javaType(f.ty)} ${f.name};"

  private def renderCtor(spec: DataStructSpec): String = {
    val params  = spec.fields.map(f => paramAnnotation(f.ty) + javaType(f.ty) + " " + f.name).mkString(", ")
    val assigns = spec.fields.map(f => s"        this.${f.name} = ${f.name};").mkString("\n")
    s"""    public ${spec.className}($params) {
       |$assigns
       |    }""".stripMargin
  }

  private def renderGetter(f: FieldSpec): String = {
    val annot = nonnullPrefix(f.ty)
    s"""$annot    public ${javaType(f.ty)} ${f.name}() {
       |        return ${f.name};
       |    }""".stripMargin
  }

  private def renderSizeBody(spec: DataStructSpec): String = {
    val fixed    = spec.fields.map(f => fixedSize(f.ty)).sum
    val variable = spec.fields.collect {
      case FieldSpec(name, FieldType.Utf8String) => s"$name.getBytes(StandardCharsets.UTF_8).length"
    }
    if (variable.isEmpty) s"$fixed" else (fixed.toString +: variable).mkString(" + ")
  }

  private def renderEncodeBody(spec: DataStructSpec): String =
    spec.fields.map { f =>
      f.ty match {
        case FieldType.I32        => s"            dst.putInt(${f.name});"
        case FieldType.I64        => s"            dst.putLong(${f.name});"
        case FieldType.Bool       => s"            dst.put((byte) (${f.name} ? 1 : 0));"
        case FieldType.Utf8String =>
          s"""            byte[] ${f.name}Bytes = ${f.name}.getBytes(StandardCharsets.UTF_8);
             |            dst.putInt(${f.name}Bytes.length);
             |            dst.put(${f.name}Bytes);""".stripMargin
        case FieldType.Bytes         => s"            dst.putInt(${f.name}.length); dst.put(${f.name});"
        case FieldType.StringList    => "            // StringList unreachable in DataStruct" // unreachable
        case FieldType.RemoteHandle  => s"            dst.putInt(${f.name}.id());"
        case FieldType.DataStruct(_) => s"            ${f.name}.encodeInto(dst);"
      }
    }.mkString("\n")

  private def renderDecodeBody(spec: DataStructSpec): String =
    spec.fields.map { f =>
      f.ty match {
        case FieldType.I32        => s"        int ${f.name} = __buf.getInt();"
        case FieldType.I64        => s"        long ${f.name} = __buf.getLong();"
        case FieldType.Bool       => s"        boolean ${f.name} = __buf.get() != 0;"
        case FieldType.Utf8String =>
          s"""        int ${f.name}Len = __buf.getInt();
             |        byte[] ${f.name}Buf = new byte[${f.name}Len];
             |        __buf.get(${f.name}Buf);
             |        String ${f.name} = new String(${f.name}Buf, StandardCharsets.UTF_8);""".stripMargin
        case FieldType.Bytes =>
          s"""        int ${f.name}Len = __buf.getInt();
             |        byte[] ${f.name} = new byte[${f.name}Len];
             |        __buf.get(${f.name});""".stripMargin
        case FieldType.StringList =>
          s"        String[] ${f.name} = new String[0]; // unreachable" // data structs don't carry StringLists
        case FieldType.RemoteHandle =>
          s"        net.kurobako.cef4j.ipc.session.RemoteHandle ${f.name} = " +
            s"new net.kurobako.cef4j.ipc.session.RemoteHandle(__buf.getInt());"
        case FieldType.DataStruct(cefName) =>
          val cls = SpecDeriver.cefStructToClassName(cefName)
          s"        $cls ${f.name} = $cls.decode(__buf);"
      }
    }.mkString("\n")

  private def fixedSize(ty: FieldType): Int = ty match {
    case FieldType.I32                          => 4
    case FieldType.I64                          => 8
    case FieldType.Bool                         => 1
    case FieldType.Utf8String | FieldType.Bytes => 4 // length prefix only
    case FieldType.StringList                   => 4 // unreachable
    case FieldType.RemoteHandle                 => 4
    case FieldType.DataStruct(_)                => 0 // size is fully variable
  }

  private def javaType(ty: FieldType): String = ty match {
    case FieldType.I32                 => "int"
    case FieldType.I64                 => "long"
    case FieldType.Bool                => "boolean"
    case FieldType.Utf8String          => "String"
    case FieldType.Bytes               => "byte[]"
    case FieldType.StringList          => "String[]" // unreachable in data structs
    case FieldType.RemoteHandle        => "net.kurobako.cef4j.ipc.session.RemoteHandle"
    case FieldType.DataStruct(cefName) => SpecDeriver.cefStructToClassName(cefName)
  }

  private def paramAnnotation(ty: FieldType): String = ty match {
    case FieldType.Utf8String | FieldType.Bytes | FieldType.StringList | FieldType.RemoteHandle |
        FieldType.DataStruct(_) =>
      "@Nonnull "
    case _ => ""
  }

  private def nonnullPrefix(ty: FieldType): String = ty match {
    case FieldType.Utf8String | FieldType.Bytes | FieldType.StringList | FieldType.RemoteHandle |
        FieldType.DataStruct(_) =>
      "    @Nonnull\n"
    case _ => ""
  }
}
