set(CEF4J_SYSTEM_PROCESSOR aarch64)
set(CEF4J_HOST_PROCESSOR_REGEX "^(aarch64|arm64|ARM64)$")
set(CEF4J_TARGET_TRIPLE aarch64-linux-gnu)
set(CEF4J_EXTRA_FLAGS "")
include("${CMAKE_CURRENT_LIST_DIR}/linux-common.cmake")
