chromium.version=150.0.7871.213
v8.revision=3063ea3a0737a3fc4d4ed3babd595f1cace1e6ac
browser.source=https://chromium.googlesource.com/chromium/src/+/refs/tags/150.0.7871.213/third_party/blink/public/devtools_protocol/
javascript.source=https://chromium.googlesource.com/v8/v8/+/3063ea3a0737a3fc4d4ed3babd595f1cace1e6ac/include/js_protocol.pdl
source.license=BSD-3-Clause
